[package]
name = "fm"
version = "0.1.0"
authors = ["Finn Hediger <finn.hediger@thurweb.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "*"
termion = "*"
